#!/usr/bin/env php
<?php
declare(strict_types=1);

use Arkitect\CLI\Check;
use Symfony\Component\Console\Application;

require __DIR__.'/vendor/autoload.php';

$application = new Application();

$application->add(new Check());

$application->run();