#!/usr/bin/env php
<?php
declare(strict_types=1);

use Arkitect\CLI\PhpArkitectApplication;

require __DIR__ . '/../vendor/autoload.php';

$application = new PhpArkitectApplication();

$application->run();