name: Architectural test

on:
    push:

permissions:
  contents: read

jobs:
    phparkitect:
        name: PHPArkitect

        runs-on: ubuntu-latest

        steps:
            - name: "Checkout"
              uses: actions/checkout@v6

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  tools: composer:v2.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Install dependencies
              run: composer install --prefer-dist

            - name: PHPArkitect
              run: php bin-stub/phparkitect check
