name: Arkitect

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      #if: steps.composer-cache.outputs.cache-hit != 'true'
      uses: php-actions/composer@v5
      with:
        args: --prefer-source
        composer_version: 2
        php_version: 7.4
    - name: "Compile phparkitect phar"
      run: ./bin/box build -c ./box.json

    - name: "Upload phar file artifact"
      uses: actions/upload-artifact@v2
      with:
        name: phparkitect.phar
        path: phparkitect.phar