name: Update CONTRIBUTORS file
on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: minicli/action-contributors@adc68c92715e07f0f39e7cdfe6397ea37e25b7ae # v3
        name: "Update a projects CONTRIBUTORS file"
        env:
          CONTRIB_REPOSITORY: 'phparkitect/arkitect'
          CONTRIB_OUTPUT_FILE: 'CONTRIBUTORS.md'
      - name: Commit changes
        uses: test-room-7/action-update-file@6b8249d09d5926fbae288c0bb640757f09ec7ce0 # v2.1.0
        with:
          file-path: 'CONTRIBUTORS.md'
          commit-msg: Update Contributors
          github-token: ${{ secrets.GITHUB_TOKEN }}
