name: Update CONTRIBUTORS file
on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:
jobs:
  main:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: minicli/action-contributors@v3.1
        name: 'Update a projects CONTRIBUTORS file'
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: 'CONTRIBUTORS.md'
          commit-msg: Update Contributors
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          CONTRIB_REPOSITORY: 'phparkitect/arkitect'
          CONTRIB_OUTPUT_FILE: 'CONTRIBUTORS.md'